name: Day9 workflow

on:
    push:
        branches: [ "day9" ]

jobs:
    build:
        runs-on: ubuntu-20.04
        container: python:3.9-slim
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements_day9.txt
            
            - name: Run nosetests
              run: cd day9 && nosetests

            - name: Execute solver script
              run: cd day9 && python solve_day9.py
