name: Day13 workflow

on:
    push:
        branches: [ "day13" ]

jobs:
    build:
        runs-on: ubuntu-20.04
        container: python:3.9-slim
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements_day13.txt
            
            - name: Run nosetests
              run: cd day13 && nosetests

            - name: Execute solver script
              run: cd day13 && python solve_day13.py
