name: Day14 workflow

on:
    push:
        branches: [ "day14" ]

jobs:
    build:
        runs-on: ubuntu-20.04
        container: python:3.9-slim
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements_day14.txt
            
            - name: Run nosetests
              run: cd day14 && nosetests

            - name: Execute solver script
              run: cd day14 && python solve_day14.py
