name: Day{NUM} workflow

on:
    push:
        branches: [ "{DAY_NUM}" ]

jobs:
    build:
        runs-on: ubuntu-18.04
        container: python:3.9-slim
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements_{DAY_NUM}.txt
            
            - name: Run nosetests
              run: cd {DAY_NUM} && nosetests
