name: Day7 workflow

on:
    push:
        branches: [ "day7" ]

jobs:
    build:
        runs-on: ubuntu-18.04
        container: python:3.9-slim
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements_day7.txt
            
            - name: Run nosetests
              run: cd day7 && nosetests
